import 'package:flutter/material.dart';
import 'creator_work_item.dart';

/// Pre-populated mock works datasets for the creator works list.
abstract final class MockCreatorWorksData {
  static const List<CreatorWorkItem> items = [
    CreatorWorkItem(
      id: 'work_1',
      brandName: 'UrbanKicks Studio',
      dealId: '#UK-9402',
      campaignTitle: 'Sneaker Gen-2 Launch Drop',
      category: 'Streetwear & Lifestyle',
      status: 'In Progress',
      agreedFee: '₹50,000',
      timeline: '15 Oct – 15 Dec',
      durationSpecs: '2 Months • 1x 4K Reel + 2x Stories',
      milestonesCompleted: 2,
      milestonesTotal: 3,
      progressRatio: 0.66,
      nextStep: 'Next: Draft Review',
      nextStepIcon: Icons.flag_rounded,
      actionButtonText: 'View Details',
      escrowLockedAmount: '₹40,000',
    ),
    CreatorWorkItem(
      id: 'work_2',
      brandName: 'FitFuel Nutrition',
      dealId: '#FF-3301',
      campaignTitle: 'Summer Hydration Energy Drink',
      category: 'Fitness & Nutrition',
      status: 'Accepted',
      agreedFee: '₹35,000',
      timeline: '01 Nov – 01 Dec',
      durationSpecs: '1 Month • 2x Shorts / Reels',
      milestonesCompleted: 1,
      milestonesTotal: 3,
      progressRatio: 0.33,
      nextStep: 'Production Window Active',
      nextStepIcon: Icons.videocam_rounded,
      actionButtonText: 'View Details',
      escrowLockedAmount: '₹35,000',
    ),
    CreatorWorkItem(
      id: 'work_3',
      brandName: 'Aura Audio Tech',
      dealId: '#AA-7712',
      campaignTitle: 'Wireless Pro ANC Earbuds Review',
      category: 'Tech & Gadgets',
      status: 'Paid',
      agreedFee: '₹42,000',
      timeline: '01 Sep – 15 Oct',
      durationSpecs: '1.5 Months • 1x YouTube Video + Carousel',
      milestonesCompleted: 3,
      milestonesTotal: 3,
      progressRatio: 1.0,
      nextStep: 'Invoice #CR-89420',
      nextStepIcon: Icons.receipt_long_rounded,
      actionButtonText: 'View Summary',
      escrowLockedAmount: '₹0',
    ),
    CreatorWorkItem(
      id: 'work_4',
      brandName: 'Silk & Stone Luxury',
      dealId: '#SS-1049',
      campaignTitle: 'Festive Velvet Collection Showcase',
      category: 'Fashion & Luxury',
      status: 'Applied',
      agreedFee: '₹75,000',
      timeline: '10 Nov – 10 Jan',
      durationSpecs: '2 Months • 2x High-production Reels',
      milestonesCompleted: 0,
      milestonesTotal: 2,
      progressRatio: 0.0,
      nextStep: 'Submitted 2 days ago',
      nextStepIcon: Icons.send_rounded,
      actionButtonText: 'Pitch Details',
      escrowLockedAmount: '₹0',
    ),
  ];
}
