import 'package:flutter/material.dart';
import '../../../../core/constants/app_assets.dart';
import 'creator_opportunity_model.dart';

const List<CreatorOpportunityModel> mockCreatorOpportunities = [
  CreatorOpportunityModel(
    id: 'opp-1',
    brandName: 'UrbanKicks Studio',
    campaignTitle: 'Sneaker Gen-2 Launch Drop',
    avatarUrl: AppAssets.brandAvatar1,
    badgeText: 'Verified Escrow',
    badgeIcon: Icons.verified_user_rounded,
    closesIn: 'Closes in 2d',
    assuredBudget: '₹50,000',
    budgetNote: 'Fixed + 5% Affiliate',
    duration: '2 months',
    category: 'Streetwear & Lifestyle',
    deliverable: '1x Reel + 2x Stories',
    deliverableIcon: Icons.video_stable_rounded,
  ),
  CreatorOpportunityModel(
    id: 'opp-2',
    brandName: 'FitFuel Nutrition',
    campaignTitle: 'Summer Hydration Energy Drink',
    avatarUrl: AppAssets.brandAvatar2,
    badgeText: 'Fast Fill • 4 Slots',
    badgeIcon: Icons.local_fire_department_rounded,
    closesIn: 'Closes in 5d',
    assuredBudget: '₹35,000',
    budgetNote: 'Milestone Payments',
    duration: '1 month',
    category: 'Fitness & Wellness',
    deliverable: '2x Shorts / Reels',
    deliverableIcon: Icons.smart_display_rounded,
  ),
  CreatorOpportunityModel(
    id: 'opp-3',
    brandName: 'Aura Audio Tech',
    campaignTitle: 'Wireless Pro ANC Earbuds Review',
    avatarUrl: AppAssets.brandAvatar3,
    badgeText: 'Hardware Unit Included',
    badgeIcon: Icons.reviews_rounded,
    closesIn: 'Closes in 6d',
    assuredBudget: '₹42,000',
    budgetNote: '+ Sample Worth ₹14,999',
    duration: '1.5 months',
    category: 'Tech & Electronics',
    deliverable: '1x YouTube Video & Carousel',
    deliverableIcon: Icons.headphones_rounded,
  ),
  CreatorOpportunityModel(
    id: 'opp-4',
    brandName: 'Silk & Stone Luxury',
    campaignTitle: 'Festive Velvet Collection Showcase',
    avatarUrl: AppAssets.brandAvatar4,
    badgeText: 'Premium Brand Tier',
    badgeIcon: Icons.diamond_rounded,
    closesIn: 'Closes in 3d',
    assuredBudget: '₹75,000',
    budgetNote: 'Exclusive Rights 60 Days',
    duration: '2 months',
    category: 'Luxury Fashion',
    deliverable: '2x High-production Reels',
    deliverableIcon: Icons.auto_fix_high_rounded,
  ),
];
